export type Page =
  | "login"
  | "workspaces"
  | "invitations"
  | "home"
  | "profile"
  | "notifications"
  | "tasks"
  | "group-tasks"
  | "requests-active"
  | "requests-completed"
  | "md-departments"
  | "md-positions"
  | "md-locations"
  | "start"
  | "business-processes"
