export type Page =
  | "home"
  | "profile"
  | "notifications"
  | "tasks"
  | "group-tasks"
  | "requests-active"
  | "requests-completed"
  | "md-departments"
  | "md-positions"
  | "md-locations"
